blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://docs.factoryknowledge.com
    about: Check our documentation for answers to common questions
  - name: Community Support
    url: https://github.com/factoryknowledge/community/discussions
    about: Ask questions and discuss with the community
  - name: Security Issue
    url: mailto:security@factoryknowledge.com
    about: Please report security vulnerabilities via email